/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_amd_aparapi_KernelRunner */

#ifndef _Included_com_amd_aparapi_KernelRunner
#define _Included_com_amd_aparapi_KernelRunner
#ifdef __cplusplus
extern "C" {
#endif
#undef com_amd_aparapi_KernelRunner_ARG_BOOLEAN
#define com_amd_aparapi_KernelRunner_ARG_BOOLEAN 1L
#undef com_amd_aparapi_KernelRunner_ARG_BYTE
#define com_amd_aparapi_KernelRunner_ARG_BYTE 2L
#undef com_amd_aparapi_KernelRunner_ARG_FLOAT
#define com_amd_aparapi_KernelRunner_ARG_FLOAT 4L
#undef com_amd_aparapi_KernelRunner_ARG_INT
#define com_amd_aparapi_KernelRunner_ARG_INT 8L
#undef com_amd_aparapi_KernelRunner_ARG_DOUBLE
#define com_amd_aparapi_KernelRunner_ARG_DOUBLE 16L
#undef com_amd_aparapi_KernelRunner_ARG_LONG
#define com_amd_aparapi_KernelRunner_ARG_LONG 32L
#undef com_amd_aparapi_KernelRunner_ARG_SHORT
#define com_amd_aparapi_KernelRunner_ARG_SHORT 64L
#undef com_amd_aparapi_KernelRunner_ARG_ARRAY
#define com_amd_aparapi_KernelRunner_ARG_ARRAY 128L
#undef com_amd_aparapi_KernelRunner_ARG_PRIMITIVE
#define com_amd_aparapi_KernelRunner_ARG_PRIMITIVE 256L
#undef com_amd_aparapi_KernelRunner_ARG_READ
#define com_amd_aparapi_KernelRunner_ARG_READ 512L
#undef com_amd_aparapi_KernelRunner_ARG_WRITE
#define com_amd_aparapi_KernelRunner_ARG_WRITE 1024L
#undef com_amd_aparapi_KernelRunner_ARG_LOCAL
#define com_amd_aparapi_KernelRunner_ARG_LOCAL 2048L
#undef com_amd_aparapi_KernelRunner_ARG_GLOBAL
#define com_amd_aparapi_KernelRunner_ARG_GLOBAL 4096L
#undef com_amd_aparapi_KernelRunner_ARG_CONSTANT
#define com_amd_aparapi_KernelRunner_ARG_CONSTANT 8192L
#undef com_amd_aparapi_KernelRunner_ARG_ARRAYLENGTH
#define com_amd_aparapi_KernelRunner_ARG_ARRAYLENGTH 16384L
#undef com_amd_aparapi_KernelRunner_ARG_APARAPI_BUF
#define com_amd_aparapi_KernelRunner_ARG_APARAPI_BUF 32768L
#undef com_amd_aparapi_KernelRunner_ARG_EXPLICIT
#define com_amd_aparapi_KernelRunner_ARG_EXPLICIT 65536L
#undef com_amd_aparapi_KernelRunner_ARG_EXPLICIT_WRITE
#define com_amd_aparapi_KernelRunner_ARG_EXPLICIT_WRITE 131072L
#undef com_amd_aparapi_KernelRunner_ARG_OBJ_ARRAY_STRUCT
#define com_amd_aparapi_KernelRunner_ARG_OBJ_ARRAY_STRUCT 262144L
#undef com_amd_aparapi_KernelRunner_ARG_APARAPI_BUF_HAS_ARRAY
#define com_amd_aparapi_KernelRunner_ARG_APARAPI_BUF_HAS_ARRAY 524288L
#undef com_amd_aparapi_KernelRunner_ARG_APARAPI_BUF_IS_DIRECT
#define com_amd_aparapi_KernelRunner_ARG_APARAPI_BUF_IS_DIRECT 1048576L
#undef com_amd_aparapi_KernelRunner_JNI_FLAG_ENABLE_PROFILING
#define com_amd_aparapi_KernelRunner_JNI_FLAG_ENABLE_PROFILING 1L
#undef com_amd_aparapi_KernelRunner_JNI_FLAG_USE_GPU
#define com_amd_aparapi_KernelRunner_JNI_FLAG_USE_GPU 2L
#undef com_amd_aparapi_KernelRunner_JNI_FLAG_ENABLE_VERBOSE_JNI
#define com_amd_aparapi_KernelRunner_JNI_FLAG_ENABLE_VERBOSE_JNI 4L
/*
 * Class:     com_amd_aparapi_KernelRunner
 * Method:    initJNI
 * Signature: (Lcom/amd/aparapi/Kernel;III)J
 */
JNIEXPORT jlong JNICALL Java_com_amd_aparapi_KernelRunner_initJNI
  (JNIEnv *, jclass, jobject, jint, jint, jint);

/*
 * Class:     com_amd_aparapi_KernelRunner
 * Method:    buildProgramJNI
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_amd_aparapi_KernelRunner_buildProgramJNI
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_amd_aparapi_KernelRunner
 * Method:    setArgsJNI
 * Signature: (J[Lcom/amd/aparapi/KernelRunner/KernelArg;I)I
 */
JNIEXPORT jint JNICALL Java_com_amd_aparapi_KernelRunner_setArgsJNI
  (JNIEnv *, jobject, jlong, jobjectArray, jint);

/*
 * Class:     com_amd_aparapi_KernelRunner
 * Method:    runKernelJNI
 * Signature: (JIIZZI)I
 */
JNIEXPORT jint JNICALL Java_com_amd_aparapi_KernelRunner_runKernelJNI
  (JNIEnv *, jobject, jlong, jint, jint, jboolean, jboolean, jint);

/*
 * Class:     com_amd_aparapi_KernelRunner
 * Method:    disposeJNI
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_amd_aparapi_KernelRunner_disposeJNI
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_amd_aparapi_KernelRunner
 * Method:    getLocalSizeJNI
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_com_amd_aparapi_KernelRunner_getLocalSizeJNI
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     com_amd_aparapi_KernelRunner
 * Method:    getExtensions
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_amd_aparapi_KernelRunner_getExtensions
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_amd_aparapi_KernelRunner
 * Method:    getJNI
 * Signature: (JLjava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_com_amd_aparapi_KernelRunner_getJNI
  (JNIEnv *, jobject, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
