/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_amd_aparapi_KernelRunner_UsedByJNICode */

#ifndef _Included_com_amd_aparapi_KernelRunner_UsedByJNICode
#define _Included_com_amd_aparapi_KernelRunner_UsedByJNICode
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
