/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_aopencl_clinfo_MainActivity */

#ifndef _Included_org_aopencl_clinfo_MainActivity
#define _Included_org_aopencl_clinfo_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_aopencl_clinfo_MainActivity
 * Method:    getClInfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_aopencl_clinfo_MainActivity_getClInfo
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
